version: '3.8'

services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - skywalking-network

  # SkyWalking OAP Server
  oap:
    image: apache/skywalking-oap-server:8.7.0-es7
    container_name: skywalking-oap-server
    depends_on:
      - elasticsearch
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_HEALTH_CHECKER=default
      - SW_TELEMETRY=prometheus
    ports:
      - "11800:11800"  # gRPC端口
      - "12800:12800"  # HTTP端口
    networks:
      - skywalking-network

  # SkyWalking UI
  ui:
    image: apache/skywalking-ui:8.7.0
    container_name: skywalking-ui
    depends_on:
      - oap
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap-server:12800
    ports:
      - "8080:8080"
    networks:
      - skywalking-network

  # 您的应用容器
  dubbo-consumer-app:
    build: .
    container_name: dubbo-consumer-app
    environment:
      - SW_AGENT_NAME=dubbo-consumer
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap-server:11800
      - SW_GRPC_LOG_SERVER_HOST=skywalking-oap-server:11800
      - SW_GRPC_LOG_SERVER_PORT=11800
    ports:
      - "8087:8087"
    depends_on:
      - oap
    networks:
      - skywalking-network

volumes:
  elasticsearch_data:

networks:
  skywalking-network:
    driver: bridge 