server:
  port: 8745

spring:
  application:
    name: dubbo-provider-a

dubbo:
  application:
    name: dubbo-provider-a
  protocol:
    name: dubbo # 确保协议名称为 dubbo
    host: 0.0.0.0 # 设置主机地址
    port: 8745 # 确保端口号为 20880
  registry:
    address: N/A # 禁用注册中心
  scan:
    base-packages: com.example.provider # 指定扫描的包路径

user:
  sys: 1043199