kafka:
  bootstrap_servers: "192.168.100.6:9092"
  group_id: "skywalking-segments-consumer-group-myself"
  #topic: "topic-dics-long-skywalking-segments"
  topic: "test_flink_task"
  auto_offset_reset: "earliest"
  poll_interval_ms: 200   # Poll interval in milliseconds (added for dynamic control)

clickhouse:
  schema_name: default       # Database schema name
  table_name: events         # Table name
  url: jdbc:clickhouse://192.168.100.6:8123/default?use_time_zone=UTC+8&use_server_time_zone=UTC+8
  username: root
  password: "123456"

batch:
  size: 2         # Number of spans per batch insert
  interval: 200    # Batch insert interval (milliseconds)

add_columns_interval: 80000  # Execute addColumns method every add_columns_interval milliseconds