CREATE TABLE events (
    trace_id String,
    trace_segment_id String,
    service Nullable(String),
    service_instance Nullable(String),
    is_size_limited Nullable(UInt8),
    span_id Int32,
    parent_span_id Int32,
    start_time DateTime64(3),
    end_time DateTime64(3),
    operation_name Nullable(String),
    peer Nullable(String),
    span_type Nullable(String),
    span_layer Nullable(String),
    component_id Nullable(Int32),
    is_error Nullable(UInt8),
    skip_analysis Nullable(UInt8),
    refs_ref_type Nullable(String),
    refs_trace_id Nullable(String),
    refs_parent_trace_segment_id Nullable(String),
    refs_parent_span_id Nullable(Int32),
    refs_parent_service Nullable(String),
    refs_parent_service_instance Nullable(String),
    refs_parent_endpoint Nullable(String),
    refs_network_address_used_at_peer Nullable(String),
    tag_status_code Nullable(String),
    tag_method_access_count_type_int64 Nullable(Int64),
    log_error_kind Nullable(String),
    log_event Nullable(String),
    log_forward_url Nullable(String),
    log_message Nullable(String),
    log_stack Nullable(String),
    tag_Available_Memory_type_Int64 Nullable(Int64),
    tag_Processor_Name Nullable(String),
    tag_Total_Memory_type_Int64 Nullable(Int64),
    tag_application_name Nullable(String),
    tag_db_instance Nullable(String),
    tag_db_statement Nullable(String),
    tag_db_type Nullable(String),
    tag_dc Nullable(String),
    tag_dubbo_local_host Nullable(String),
    tag_dubbo_remote_host Nullable(String),
    tag_dubbo_remote_port Nullable(String),
    tag_env_APP_VERSION Nullable(String),
    tag_env_HOME Nullable(String),
    tag_env_HOSTNAME Nullable(String),
    tag_env_JAVA_HOME Nullable(String),
    tag_env_JAVA_VERSION Nullable(String),
    tag_env_LANG Nullable(String),
    tag_env_PATH Nullable(String),
    tag_env_TZ Nullable(String),
    tag_error_context Nullable(String),
    tag_error_message Nullable(String),
    tag_error_method Nullable(String),
    tag_error_parameters Nullable(String),
    tag_error_stack_trace Nullable(String),
    tag_error_type Nullable(String),
    tag_http_method Nullable(String),
    tag_http_status_code Nullable(String),
    tag_http_url Nullable(String),
    tag_jvm_heap_committed_type_Int64 Nullable(Int64),
    tag_jvm_heap_init_type_Int64 Nullable(Int64),
    tag_jvm_heap_max_type_Int64 Nullable(Int64),
    tag_jvm_heap_used_type_Int64 Nullable(Int64),
    tag_jvm_name Nullable(String),
    tag_jvm_nonheap_committed_type_Int64 Nullable(Int64),
    tag_jvm_nonheap_init_type_Int64 Nullable(Int64),
    tag_jvm_nonheap_max_type_Int64 Nullable(Int64),
    tag_jvm_nonheap_used_type_Int64 Nullable(Int64),
    tag_jvm_start_time Nullable(String),
    tag_jvm_uptime Nullable(String),
    tag_jvm_vendor Nullable(String),
    tag_jvm_version Nullable(String),
    tag_methodName Nullable(String),
    tag_method_result Nullable(String),
    tag_os_arch Nullable(String),
    tag_os_name Nullable(String),
    tag_os_version Nullable(String),
    tag_rpc_context_input Nullable(String),
    tag_rpc_context_remote_application Nullable(String),
    tag_rpc_context_sw8 Nullable(String),
    tag_rpc_context_sw8_correlation Nullable(String),
    tag_rpc_context_sw8_x Nullable(String),
    tag_rpc_method_name Nullable(String),
    tag_rpc_object_attachment_input Nullable(String),
    tag_rpc_object_attachment_remote_application Nullable(String),
    tag_rpc_object_attachment_sw8 Nullable(String),
    tag_rpc_object_attachment_sw8_correlation Nullable(String),
    tag_rpc_object_attachment_sw8_x Nullable(String),
    tag_rpc_protocol Nullable(String),
    tag_rpc_role Nullable(String),
    tag_rpc_service_interface Nullable(String),
    tag_rpc_service_url Nullable(String),
    tag_sys Nullable(String),
    tag_thread_count_type_Int64 Nullable(Int64),
    tag_thread_current_cpu_time_type_Int64 Nullable(Int64),
    tag_thread_current_user_time_type_Int64 Nullable(Int64),
    tag_thread_daemon_count_type_Int64 Nullable(Int64),
    tag_thread_peak_count_type_Int64 Nullable(Int64),
    tag_thread_total_started_count_type_Int64 Nullable(Int64),
    tag_url Nullable(String)
) ENGINE = MergeTree()
PARTITION BY toDate(start_time)
ORDER BY (start_time, trace_id);

CREATE TABLE new_key
(
    keyName String,
    keyType String,
    isCreated Boolean,
    createTime DateTime
)
ENGINE = MergeTree()
ORDER BY keyName;

CREATE TABLE IF NOT EXISTS param_config (
    namespace String,
    operatorClass String,
    paramKey String,
    paramValue String,
    createTime DateTime
) ENGINE = MergeTree()
ORDER BY (namespace, operatorClass, paramKey);

INSERT INTO param_config VALUES ('flinkParam', 'AggregateOperator', 'windowSize', '22', now());

CREATE TABLE IF NOT EXISTS flink_operator_agg_result (
    window_start  DateTime64(3),
    windowSize    Int32,
    operator_name String DEFAULT '',
    operator_class String DEFAULT '',
    service       String DEFAULT '',
    instance      Nullable(String),
    method        Nullable(String),
    avg_duration  Nullable(Float64),
    max_duration  Nullable(Int64),
    error_rate    Nullable(Float64),
    data_center   Nullable(String),
    region        Nullable(String),
    env           Nullable(String),
    total_count   Nullable(Int64),
    error_count   Nullable(Int64),
    success_count Nullable(Int64)
) ENGINE = MergeTree()
PARTITION BY toDate(window_start)
ORDER BY (window_start, service, operator_name);

CREATE TABLE IF NOT EXISTS hourly_alarm_rules (
    hour_of_day UInt8,
    service String,
    operator_name String,
    operator_class String,
    avg_duration_low Float64,
    avg_duration_mid Float64,
    avg_duration_high Float64,
    max_duration_low Float64,
    max_duration_mid Float64,
    max_duration_high Float64,
    success_rate_low Float64,
    success_rate_mid Float64,
    success_rate_high Float64,
    traffic_volume_low Float64,
    traffic_volume_mid Float64,
    traffic_volume_high Float64,
    alarm_template String,
    analysis_days UInt8,
    sample_count UInt32,
    generated_time DateTime DEFAULT now(),
    last_updated DateTime DEFAULT now(),
    version UInt32 DEFAULT 1,
    PRIMARY KEY (hour_of_day, service, operator_name)
) ENGINE = MergeTree()
ORDER BY (hour_of_day, service, operator_name); 